drop table if exists CREDIT_CARD_STORE;
drop table if exists USER_STORE;

create sequence if not exists SEQ_CREDIT_CARD_STORE;
create sequence if not exists SEQ_USER_STORE;


create table USER_STORE
(
    USER_ID           	NUMBER NOT NULL,
    NAME				VARCHAR2(1000 CHAR) NOT NULL,
    USER_STATUS     	VARCHAR2(50 CHAR) NOT NULL,
    CREATED_TIMESTAMP   TIMESTAMP (6) NOT NULL,
    CONSTRAINT PK_USER_STORE PRIMARY KEY (USER_ID)
);



create table CREDIT_CARD_STORE
(
    CARD_ID      		NUMBER NOT NULL,
    USER_ID      		NUMBER NOT NULL,
    CARD_NUMBER  		VARCHAR2(30 CHAR) NOT NULL,
    CARD_PROCESSOR   	VARCHAR2(50 CHAR) NOT NULL,
    CODE    			VARCHAR2(50 CHAR) NOT NULL,
    CARD_LIMIT    		NUMBER NOT NULL,
    CARD_BALANCE    	NUMBER NOT NULL,
    CARD_STATUS    		VARCHAR2(50 CHAR) NOT NULL,
    CARD_EXPIRY   		VARCHAR2(50 CHAR) NOT NULL,
    CREATED_TIMESTAMP   TIMESTAMP (6) NOT NULL,
    CONSTRAINT PK_CARD_STORE PRIMARY KEY (CARD_ID),
    CONSTRAINT UK_CARD_STORE UNIQUE (CARD_NUMBER),
    CONSTRAINT FK_CS_US FOREIGN KEY (USER_ID) REFERENCES USER_STORE (USER_ID)

);